name: "Build"
on: [push, pull_request]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout files
          uses: @action/checkout@v2
        - name: Setup node
          uses: @action/setup-node@v2
        - name: Build
          run: npm run build