name: "Build"
on: [push, pull_request]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - uses: @action/checkout@v2
        - uses: @action/setup-node@v2
        - run: npm run build